# This is a SecretProviderClass example using system-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-system-msi
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"    # Set to true for using managed identity
    userAssignedIdentityID: "d2fa370e-6da5-4aa3-b5e1-812170efc23e"      # If empty, then defaults to use the system assigned identity on the VM
    keyvaultName: nextopsakv01
    cloudName: "AzurePublicCloud"                   # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: mysql-password
          objectType: secret        # object types: secret, key, or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: mysql-username
          objectType: secret        # object types: secret, key, or cert
          objectVersion: "" 
        - |
          objectName: mysql-servername
          objectType: secret        # object types: secret, key, or cert
          objectVersion: "" 
    tenantId: 9085ff8c-8807-4ff8-a403-ea470525cda6          # The tenant ID of the key vault